import pyautogui as fc


#excluir fonte de dados antiga
fc.press('win')
fc.sleep(2)
fc.write('Explorador de Arquivos')
fc.press('enter')
fc.sleep(2)
fc.moveTo(x=89,y=335)
fc.sleep(1)
fc.click(button='left')
fc.sleep(1)
fc.moveTo(x=1335,y=54)
fc.sleep(1)
fc.click(button='left')
fc.sleep(1)
fc.write('base_open')
fc.sleep(2)
fc.press('enter')
fc.sleep(1)
fc.moveTo(x=384,y=157)
fc.sleep(1)
fc.click(button='left')
fc.click(button='left')
fc.moveTo(x=320,y=169)
fc.click(button='left')
fc.sleep(1)
fc.press('del')
fc.sleep(3)


# iniciar processo de download
fc.press('win')
fc.sleep(3)
fc.write('Edge')
fc.sleep(3)
fc.press('enter')
fc.sleep(3)
fc.moveTo(x=674,y=64)
fc.sleep(3)
fc.click(button='left')
fc.sleep(3)
fc.write('https://docs.google.com/spreadsheets/d/1gpFiyY3iahl-rTHTymcKfy4oUpSw1MlbKODe-qkPjio/')
fc.sleep(5)
fc.press('enter')
fc.sleep(5)
fc.moveTo(x=94,y=114)
fc.sleep(5)
fc.click(button='left')
fc.sleep(5)
fc.moveTo(x=310,y=357)
fc.sleep(5)
fc.moveTo(x=450,y=366)
fc.click(button='left')
fc.sleep(3)


#recortar novo download 
fc.press('win')
fc.sleep(2)
fc.write('Explorador de Arquivos')
fc.press('enter')
fc.sleep(2)
fc.moveTo(x=96,y=303)
fc.click(button='left')
fc.sleep(1)
fc.moveTo(x=263,y=197)
fc.sleep(1)
fc.click(button='left')
fc.hotkey('ctrl', 'x')
fc.sleep(1)
fc.moveTo(x=89,y=335)
fc.sleep(1)
fc.click(button='left')
fc.sleep(1)
fc.moveTo(x=1335,y=54)
fc.sleep(1)
fc.click(button='left')
fc.sleep(1)
fc.write('base_open')
fc.sleep(2)
fc.press('enter')
fc.sleep(1)
fc.moveTo(x=384,y=157)
fc.sleep(1)
fc.click(button='left')
fc.click(button='left')
fc.sleep(1)
fc.moveTo(x=590,y=273)
fc.sleep(1)
fc.hotkey('ctrl', 'v')