import pyautogui as fc


# #excluir fonte de dados antiga

# fc.moveTo(x=569,y=1058)
# fc.sleep(3)
# fc.click(button='left')
# fc.sleep(5)
# fc.moveTo(x=109,y=863)
# fc.sleep(5)
# fc.click(button='left')
# fc.moveTo(x=1789,y=194)
# fc.sleep(5)
# fc.click(button='left')
# fc.write('Fonte_Dados_Excel')
# fc.sleep(5)
# fc.press('enter')
# fc.sleep(3)
# fc.moveTo(x=391,y=249)
# fc.doubleClick()
# fc.moveTo(x=446,y=267)
# fc.sleep(5)
# fc.click(button='left')
# fc.sleep(3)
# fc.press('del')

# iniciar processo de download
fc.press('win')
fc.sleep(3)
fc.write('Edge')
fc.sleep(3)
fc.press('enter')
fc.sleep(3)
fc.moveTo(x=674,y=64)
fc.sleep(3)
fc.click(button='left')
fc.sleep(3)
fc.write('https://docs.google.com/spreadsheets/d/1gpFiyY3iahl-rTHTymcKfy4oUpSw1MlbKODe-qkPjio/')
fc.sleep(5)
fc.press('enter')
fc.sleep(5)
fc.moveTo(x=94,y=114)
fc.sleep(5)
fc.click(button='left')
fc.sleep(5)
fc.moveTo(x=310,y=357)
fc.sleep(5)
fc.moveTo(x=450,y=366)
fc.click(button='left')
fc.sleep(3)


#recortar novo download 

fc.moveTo(x=569,y=1058)
fc.click(button='left')
fc.sleep(5)
fc.moveTo(x=112,y=306)
fc.sleep(4)
fc.click(button='left')
fc.moveTo(x=352,y=294)
fc.sleep(3)
fc.click(button='left')
fc.hotkey('ctrl', 'x')

fc.sleep(5)
fc.moveTo(x=109,y=863)
fc.sleep(5)
fc.click(button='left')
fc.moveTo(x=1789,y=194)
fc.sleep(5)
fc.click(button='left')
fc.write('Fonte_Dados_Excel')
fc.sleep(5)
fc.press('enter')
fc.sleep(3)
fc.moveTo(x=391,y=249)
fc.doubleClick()
fc.moveTo(x=446,y=267)
fc.sleep(5)
fc.click(button='left')
fc.sleep(3)
fc.hotkey('ctrl', 'v')